/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    CheckBox: typeof import('./src/components/CheckBox/index.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    PincodeInput: typeof import('./src/components/PincodeInput/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchDark: typeof import('./src/components/Header/NavTools/SwitchDark.vue')['default']
    TextInput: typeof import('./src/components/TextInput/index.vue')['default']
  }
}
