/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    CheckBox: typeof import('./src/components/CheckBox/index.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HandleMobileMenu: typeof import('./src/components/Header/NavTools/HandleMobileMenu.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    MobileLogo: typeof import('./src/components/Header/NavTools/MobileLogo.vue')['default']
    MobileSidebar: typeof import('./src/components/SideBar/MobileSidebar.vue')['default']
    Modal: typeof import('./src/components/Modal/index.vue')['default']
    Navmenu: typeof import('./src/components/SideBar/Navmenu.vue')['default']
    Profile: typeof import('./src/components/Header/NavTools/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar/index.vue')['default']
    SwitchDark: typeof import('./src/components/Header/NavTools/SwitchDark.vue')['default']
    TextInput: typeof import('./src/components/TextInput/index.vue')['default']
  }
}
